site_name: GPT4All
repo_url: https://github.com/nomic-ai/gpt4all
repo_name: nomic-ai/gpt4all
site_url: https://docs.gpt4all.io
edit_uri: edit/main/docs/
site_description: GPT4All Docs - run LLMs efficiently on your hardware
copyright: Copyright &copy; 2024 Nomic, Inc
use_directory_urls: false

nav:
    - 'index.md' 
    - 'Quickstart' : 'gpt4all_desktop/quickstart.md'
    - 'Chats' : 'gpt4all_desktop/chats.md'
    - 'Models' : 'gpt4all_desktop/models.md'
    - 'LocalDocs' : 'gpt4all_desktop/localdocs.md'
    - 'Settings' : 'gpt4all_desktop/settings.md'
    - 'Chat Templates' : 'gpt4all_desktop/chat_templates.md'
    - 'Cookbook':
      - 'Local AI Chat with Microsoft Excel': 'gpt4all_desktop/cookbook/use-local-ai-models-to-privately-chat-with-microsoft-excel.md'
      - 'Local AI Chat with your Google Drive': 'gpt4all_desktop/cookbook/use-local-ai-models-to-privately-chat-with-google-drive.md'
      - 'Local AI Chat with your Obsidian Vault': 'gpt4all_desktop/cookbook/use-local-ai-models-to-privately-chat-with-Obsidian.md'
      - 'Local AI Chat with your OneDrive': 'gpt4all_desktop/cookbook/use-local-ai-models-to-privately-chat-with-One-Drive.md'
    - 'API Server':
      - 'gpt4all_api_server/home.md'
    - 'Python SDK':
      - 'gpt4all_python/home.md'
      - 'Monitoring': 'gpt4all_python/monitoring.md'
      - 'SDK Reference': 'gpt4all_python/ref.md'
    - 'Help':
      - 'FAQ': 'gpt4all_help/faq.md'
      - 'Troubleshooting': 'gpt4all_help/troubleshooting.md'

    - 'index.md'
    - 'GPT4All Chat Client': 'gpt4all_chat.md'
    - 'Bindings':
      - 'GPT4All in Python':
        - 'Generation': 'gpt4all_python.md'
        - 'Embedding': 'gpt4all_python_embedding.md'
      - 'GPT4ALL in NodeJs': 'gpt4all_typescript.md'
      - 'gpt4all_cli.md'
#    - 'Tutorials':
#      - 'gpt4all_modal.md'
    - 'Wiki':
      - 'gpt4all_faq.md'

theme:
  name: material
  palette:
    primary: white
  logo: assets/nomic.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.sections
#    - navigation.tabs
#    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - tables
  - admonition
  - codehilite:
      css_class: highlight
  - markdown_captions

extra_css:
    - css/custom.css



plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            heading_level: 4
            show_root_full_path: false
            docstring_section_style: list
  - material/social:
      cards_layout_options:
          font_family: Roboto
          description: GPT4All runs LLMs efficiently on your hardware

extra:
  generator: false
  analytics:
    provider: google
    property: G-NPXC8BYHJV
